### ISSUE TITLE
Better name for third-party cookies: Cross-site cookies

### ISSUE THREAD

**Issue by johnwilander** [w3ctag/web-without-3p-cookies#14]
Third-party cookies is a loose term and we should consider a more precise term for this standards work.

The popular understanding of third-party cookies is "first party cookies that are available and writeable in third-party contexts." Party is defined as site, and third-party as cross-site.

However, many think that third-party cookies are some special kind of cookies. But in the popular understanding described above, they aren't, they're just cookies. The most confusing part is that such third-party cookies are also first party cookies.

We are quickly approaching a reality where there will be true third-party cookies, i.e. partitioned cookies. Those _will_ be different cookies and not also be first party cookies.

Based on the above, I propose that this document uses and defines **cross-site cookies**. An alternative would be unpartitioned cookies but I think that term would miss the cross-site/third-party context part and again mix it with first party cookies which are also unpartitioned.

SameSite cookies is pretty well aligned with the notion of cross-site cookies. SameSite=none is a way to currently express that you want a cookie to be available in cross-site contexts.

If you agree, the document title would be changed to **Improving the web without cross-site cookies**.

**Comment by hadleybeeman** [comment]
Hi John! Thanks for your helpful suggestion.

We do want to be thorough, and think that adding a mention of cross-site cookies would make the document more complete.

We've made that change in [PR 15](https://github.com/w3ctag/web-without-3p-cookies/pull/15).

At the same time, most of the discussions we are in are widely relying on "third-party cookies", and we want to make sure that this document is received into those discussions. So it doesn't make sense for us to change every reference to "third-party cookies" to "cross-site cookies".

Thanks again for your help!
