### ISSUE TITLE
Movement for an Open Web (MOW) comments on W3C TAG Draft Finding

### ISSUE THREAD

**Issue by Tim-Cowen** [w3ctag/web-without-3p-cookies#19]
In italics are excerpts taken from the TAG finding followed by MOW’s comments bulleted below.

 

_There are **use cases for third-party cookies that need to be preserved**, and pitfalls we need to be careful to avoid while doing so._

 

- The only purpose for “third-party” cookies is to provide smaller organisations choice among a competitive set of solution providers to better compete against larger rivals.
- Competition among browsers to provide business-facing solutions with their consumer software does not provide media owners any choice.
- Thus, replacing third-party cookies with only the various consumer-software used by disparate site visitors to publishers’ properties distorts competition.

 

_Third party cookies (cookies set by someone other than the website being used)… increase in data collection and sharing **about people using the web** - often in a way that is opaque or incomprehensible to a web user - results in decreased individual and collective privacy._

 

- Cookies do not collect data about people.
- There is no technical difference about the capabilities cookies can be used, by first or third parties.
- The concern raised by TAG is linking digital activity to the identity of specific people.
- Cookies do not do this.
- Companies can do this, but only via authentication.
- Thus, the focus should not be on interfering with neutral transport technologies that support interoperability necessary for competition, but instead focusing on use cases limited to authentication.
- Given all browser vendors record people’s browsing history and are now increasingly remembering log-in state which discloses individuals’ identity to the consumer software manufacturer, these organizations pose a higher threat vector to consumer privacy than the vast majority of websites who rely solely on logged-out interactions.

 

_**Third-party cookies** in particular are a key technology supporting tracking networks, which have **been identified as a major threat to privacy**._

 

- Third-party cookies have not been identified as any threat to privacy.
- They pose the same level of threat as owning a home, which increases the risk of home invasion threats to privacy.
- The cookie is a text file. It is a neutral piece of technology. While bad actors can break into homes and use any technology, including spoons, to harm individuals – this does not mean spoons are identified as a threat.

 

_These tracking networks entail concentrating data in the hands of - and thus **giving greater power to - intermediaries with a presence across many sites, away from the individual sites a person is actually visiting. This centralising effect has repercussions on innovation** and accountability, beyond what is in scope for discussion here._

 

- MOW agrees that centralising more control into fewer organisations poses a major threat to innovation, competition and privacy.
- Unfortunately, the W3C TAG is proposing just this. Centralise more power and control over Personal Data into the hands of a limited set of consumer-software manufacturers.
- Many of these organisations have been identified as internet-gatekeepers who pose a large threat to democratic societies, such as referenced in the EU Digital Markets Act.
- The W3C would be well advised to stop collaborating in their efforts to fragment the web (by isolating each organisation to be only able to exchange information with the consumer-software manufacturer – thus violating laws that protect the business-initiated exchange of data, aka “interoperability”).

 

_We maintain that security and privacy are essential on **an ethical web**; a reduction in privacy also has implications for freedom of expression, supporting healthy communities and the **enhancement of individual control and power.**_

 

- MOW fully supports improving security, privacy and freedom of expression which is essential to healthy societies.
- MOW does not believe that ethics or justice can be automated into software.
- Ethics involves human judgement and cases are always fact-dependent.
- Thus, instituting one-size fits all rules or worse, rules that fit only a few, would be detrimental to the open web and definitely leave it worse than when we found it.
- MOW also supports enhancing individuals to control their identity.
- MOW disagrees that individuals should control all business decisions or even how any other individual or business must operate.
- First, as data protection regulators are increasingly publicising, individuals cannot be meaningfully informed of most business-facing decisions – thus they cannot provide informed input into such decisions.
- Second, human rights also recognise the rights of other individuals in society, not only each individual. The right to conduct a business is enshrined both in GDPR and in many other Human Rights laws.
- Freedom to conduct a business enables individual aspirations and expressions to flourish, promotes entrepreneurship and innovation, which in turn is indispensable for sustainable social and economic development, such as reducing unemployment.
- Freedom to conduct a business is also protected by the United Nations Covenant on Economic, Social and Cultural Rights (ICESCR) in Article 6(1) (the right to work) as well as more explicitly in the EU CFR Article 16 (Freedom to conduct a business).

 

_Some recent good examples of the designed-for-purpose approach include:_

- FedCM. Third-party cookies have been used to support single sign-on. FedCM is a set of technologies built to **support identity federation,** without replicating all functionality of third-party cookies.
- CHIPS. The goal of CHIPS is to allow state, **without supporting correlation** or tracking **between web sites** which don't know they are collaborating, for example, when embedding third-party services like customer service webchat.
- Fenced Frames. This provides a new top-level browsing context which **enables content from multiple parties to be embedded on a page, without the embedding site being able to communicate with the embedded site.**

 

- MOW disagrees that to compete for business-services across the open web, one must first become a dominant consumer-software manufacturer.
- MOW further disagrees that interfering with collaboration among businesses (another form of interoperability) is per se evil.
- In fact, MOW believes the contrary.
- Mashups and other forms of digital collaboration are beneficial to end users and foster greater innovation by allowing smaller sites to offer solutions that can rival those of the very largest sites – whose scale, variety and access to internal resources are cost prohibitive to all new entrants and smaller rivals.
- Unless there is evidence of a particular bad actor abusing Personal Data, then competition, innovation and choice should be supported.

 

_When we review new technologies to replace third-party cookies, we need to ensure that the replacements do not recreate the same pitfalls to privacy._

 

- MOW agrees with this position – yet questions how any technology can support the interoperable use cases required without some common entity matching activity across contexts and sites.
- Fraud detection, identity verification, frequency capping and attribution are all positive benefits of cross-context/site collection and processing of digital activity.
- Merely substituting a consumer software manufacturer for a competitive market does not reduce the possibility of risk.
- Indeed, many of the largest privacy fines in history have been levied against some of the largest consumer-facing organizations.
- Thus “pitfalls to privacy” must be determined by what data is collected and processed, not by the size of the organization collecting and processing data for business use.
- Given the data protection authority positions, which MOW shares, that consumers can never be meaningfully informed of all the various business solution providers nor all the innovative future use cases that may be informed by data, the only practical way forward is to warn users when sensitive data is shared (much like current warnings for out of data SSL records) and increase transparency of sharing through improved logging of transactions (such as required by the EU Digital Services Act).

 

_**The web must be cross-platform**, so multi-stakeholder **(in particular, multi-browser)** support for privacy-related specifications is essential if they are going to achieve the goal of increasing privacy on the web._

 

- MOW agrees with this position.
- However, the bolded text highlights that from the publisher perspective, data must be consistent across the various versions of consumer-software that visitors to sites select.
- If browsers and other internet-enabled consumer software do not support this, then organisations will require more consumers to disclose their identity – increasing risks to specific individuals and leaving the web worse than we found it.
- We can see such efforts already underway in Google’s Customer Match and Facebook’s IPA to support required business-facing solutions such as attribution.

 

_**All proposers** of new web platform technologies **are expected to be able to explain and justify the benefits and trade-offs of their proposal.** It is particularly important that proposals which aim to fill gaps left by the removal of third-party **cookies provide clear and concrete evidence that individual and collective privacy is still preserved;** especially proposals which involve profiling, **cross-context recognition**, or otherwise aggregating or sharing of web user data between parties. We encourage that **proposals claiming to improve privacy** on the web platform **undergo independent review and analysis;** **the burden of proof is on the proposers, not reviewers,** to justify additions and changes to the web platform. The benefits to web platform users of the removal of third-party cookies must not be undermined by user agents or site authors in other ways._

 

- MOW agrees with most of these positions.
- If “recognition” were defined as re-identification then we would agree with all of them.
- To date, the only beneficiaries of proposals are the proposers’ multi-national organisations. 
- All proposals require a centralised gatekeeper to collect and process Personal Data for use in business purposes – which does nothing to protect individuals from that gatekeeper.
- Indeed as highlighted by EU’s Digital Services Act and UK regulators, it is often these centralised and Very Large Online Platforms that pose the greatest risks to society.
- Until there is evidence that a proposal can provide an alternative to the features and functionality supported by third-party cookies – namely choice for small businesses among a competitive market of solution providers to help them operate and grow their business, which requires interoperability – then a proposal should be considered a de facto non-effective substitute.

**Comment by plinss** [comment]
Thanks for your feedback, we're really happy to see you agree with so many points in the document. We have considered the issues you've raised, some of these we disagree with, others we feel we have addressed.
