### ISSUE TITLE
Centralization risks of cookie alternatives?

### ISSUE THREAD

**Issue by dmarti** [w3ctag/web-without-3p-cookies#2]
In some cases, centralization effects may be a equal or greater problem for proposed alternatives than for third-party cookies.

> These tracking networks entail concentrating data in the hands of - and thus giving greater power to - intermediaries with a presence across many sites, away from the individual sites a person is actually visiting. This centralising effect has repercussions on innovation and accountability, beyond what is in scope for discussion here.

If a proposed alternative is designed with a subset of the capabilities of third-party cookies -- for example, to allow transfer of user data among sites that include the same third-party script or iframe -- then the centralization risks are similar to those of third-party cookies.

Where a proposed alternative adds noise in order to create deniability or limit cross-site identification of an individual, then third parties that can see more traffic are more likely to be able to pick a signal out of the noise. A cookie alternative that adds just the right amount of noise to tracking data might be effectively usable for tracking by a few large third parties. Adding noise on the client side might be an effective way to limit cross-site identification, so should not be ruled out entirely, but it might be appropriate to increase the noise added when sending user data to often-seen third parties, in order to make cookie alternatives equally usable for all sizes of third party, and limit incentives to increase risky centralization.

**Comment by hadleybeeman** [comment]
Hi @dmarti, and thanks for bringing this up.

We have discussed it, and think that it is already represented in the approach represented by text like this:

> The TAG considers each new technology proposal both individually, and as they fit together with the web platform as a whole. 

and 

> When we review new technologies to replace third-party cookies, we need to ensure that the replacements do not recreate the same pitfalls to privacy.

We aren't planning to cite more specific use cases or threat models in the document, since the list may continually be evolving. 

To that end, we are going to close this issue, but really appreciate you helping us to make the finding stronger!
