### ISSUE TITLE
One more potential ref

### ISSUE THREAD

**Issue by mnot** [w3ctag/web-without-3p-cookies#20]
FWIW, the current revision of the cookie specification has a few things to say that might be helpful:
  https://httpwg.org/http-extensions/draft-ietf-httpbis-rfc6265bis.html#name-privacy-considerations

**Comment by torgo** [comment]
Closed with https://github.com/w3ctag/web-without-3p-cookies/commit/7eae6c9fc52676f88065f8211ae2e061a8c79d1f - thank you @mnot!
