### ISSUE TITLE
Recommendation to deprecate 3rd party cookies before alternatives are standardized is not pragmatic

### ISSUE THREAD

**Issue by LeaVerou** [w3ctag/web-without-3p-cookies#5]
>  We are also wary of new approaches being introduced while third-party cookies are still available to authors, as this comes with a risk that more, parallel channels for privacy invasion become possible, rather than fewer. Thus, the deprecation of third-party cookies should not be dependent upon the standardisation of replacement technologies.

I don't think that's realistic to recommend, and thus undermines the credibility of the whole document.
There are several use cases mentioned in the document that could not simply stop working. Depreciation is premature when there is no alternative, and until alternatives are standardized and mature enough to be used in production, effectively there isn't.

Also, if these new channels only offer a small subset of the functionality of third party cookies, I'm not sure how "more, parallel channels for privacy invasion become possible". I thought the whole point of these alternatives is that they *don't* invade privacy?

**Comment by cynthia** [comment]
> We urge that the deprecation of third-party cookies continues across the web platform irrespective of the progress of proposals which seek to replace some of the functionality of third-party cookies. 

Is also in those lines.

**Comment by hober** [comment]
I think it's perfectly realistic for the document to recommend something that two out of three major browser engines are already doing, and that the third is actively working on.

**Comment by cynthia** [comment]
Extending previous comment: There is a chicken and an egg problem - certain implementations are unable to deprecate without a proposed replacement.

> We urge that the deprecation of third-party cookies continues across the web platform irrespective of the progress of proposals which seek to replace some of the functionality of third-party cookies. 

In particular would be an unrealistic recommendation. I would soften up the wording a bit:

> We want to emphasize that as the proposals progress, implementations should have a strong commitment and deadline toward deprecating third-party cookies.  

Will draft a PR.
