### ISSUE TITLE
Do we really want to discourage more general replacements entirely?

### ISSUE THREAD

**Issue by LeaVerou** [w3ctag/web-without-3p-cookies#7]
> We discourage more general replacements, which are at risk of recreating the same issues caused by third-party cookies in the first place.

I'm a bit concerned this could curb innovation. If, in theory, there was a generalized 3p cookie alternative that somehow prevented the undesirable use cases of 3p cookies, that would be fine. 

How about something like:

> We discourage more general replacements which recreate the same issues caused by third-party cookies.

**Comment by hober** [comment]
I think the existing wording is reasonable and should stand. Should someone come up with a general solution that has the privacy properties we'd like, we can change the wording then, when there's actual evidence that that's possible.

**Comment by LeaVerou** [comment]
How about:

> We discourage more general replacements, as they tend to recreate the same issues caused by third-party cookies.

**Comment by plinss** [comment]
Or:
> Any proposal that acts as a general-purpose replacement for third-party cookies would need to be accompanied by evidence that it does not recreate the same issues.

**Comment by torgo** [comment]
Suggest "evidence" instead of proof.
